# Day 09: NumPy Array Creation and Data Types

**Dataset:** `Iris_Dataset.csv`

This notebook creates NumPy arrays and explores their shape, dimensions, size, data types,
and basic operations, using real values pulled directly from the Iris dataset.

## 1. Import Libraries and Load the Dataset

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("../datasets/Iris_Dataset.csv")

# Preview the data
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
# Basic info about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    str    
dtypes: float64(4), str(1)
memory usage: 6.0 KB


## 2. One-Dimensional Arrays

A 1D array is a single row (or column) of values, which is created with `np.array()`.

**Create a 1D array from a real column**

In [ ]:
sepal_length = np.array(df["sepal length (cm)"])
print(sepal_length[:10])
print(type(sepal_length))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]
<class 'numpy.ndarray'>


**Create a 1D array manually from a plain Python list**

In [ ]:
manual_array = np.array([1, 2, 3, 4, 5])
print(manual_array)
print(type(manual_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 3. Two-Dimensional Arrays

A 2D array has rows and columns, which useful for representing an entire table of features at
once.

**Create a 2D array from four real columns**

In [ ]:
feature_columns = ["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]
features = np.array(df[feature_columns])

print(features[:5])
print(type(features))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
<class 'numpy.ndarray'>


**Create a 2D array manually**

In [ ]:
manual_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(manual_2d_array)

[[1 2 3]
 [4 5 6]]


## 4. Array Attributes

Every NumPy array has attributes that describe its structure: `shape`, `ndim`, `size`, and
`dtype`.

**Attributes of the 1D array (`sepal_length`)**

In [ ]:
print("shape:", sepal_length.shape)   # (150,) - 150 values in one dimension
print("ndim:", sepal_length.ndim)      # 1 - one dimension
print("size:", sepal_length.size)      # 150 - total number of elements
print("dtype:", sepal_length.dtype)    # the data type of the elements

shape: (150,)
ndim: 1
size: 150
dtype: float64


**Attributes of the 2D array (`features`)**

In [ ]:
print("shape:", features.shape)   # (150, 4) - 150 rows, 4 columns
print("ndim:", features.ndim)      # 2 - two dimensions
print("size:", features.size)      # 600 - total number of elements (150 x 4)
print("dtype:", features.dtype)

shape: (150, 4)
ndim: 2
size: 600
dtype: float64


**Arrays can hold different data types — creating an array of strings**

In [ ]:
species = np.array(df["target"])
print(species[:5])
print("dtype:", species.dtype)   # a string dtype, not numeric

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
dtype: object


## 5. Numerical Operations on Arrays

**Summary statistics**

In [ ]:
print("Mean sepal length:", sepal_length.mean())
print("Max sepal length:", sepal_length.max())
print("Min sepal length:", sepal_length.min())
print("Sum of sepal length:", sepal_length.sum())
print("Standard deviation:", sepal_length.std())

Mean sepal length: 5.843333333333334
Max sepal length: 7.9
Min sepal length: 4.3
Sum of sepal length: 876.5
Standard deviation: 0.8253012917851409


**Element-wise arithmetic (every value is affected at once, with no loop needed)**

In [ ]:
sepal_length_doubled = sepal_length * 2
sepal_length_plus_one = sepal_length + 1

print(sepal_length[:5])
print(sepal_length_doubled[:5])
print(sepal_length_plus_one[:5])

[5.1 4.9 4.7 4.6 5. ]
[10.2  9.8  9.4  9.2 10. ]
[6.1 5.9 5.7 5.6 6. ]


**Operations between two arrays of the same shape**

In [ ]:
sepal_width = np.array(df["sepal width (cm)"])

# Adding two full columns together, element by element
sepal_total = sepal_length + sepal_width
print(sepal_total[:5])

[8.6 7.9 7.9 7.7 8.6]


**Boolean masking — filtering an array based on a condition**

In [ ]:
long_sepals = sepal_length[sepal_length > 6]
print(long_sepals[:10])
print("Number of flowers with sepal length > 6:", len(long_sepals))

[7.  6.4 6.9 6.5 6.3 6.6 6.1 6.7 6.2 6.1]
Number of flowers with sepal length > 6: 61


**Statistics on the full 2D array, per column**

In [ ]:
column_means = features.mean(axis=0)
print("Mean of each column (sepal length, sepal width, petal length, petal width):")
print(column_means)

Mean of each column (sepal length, sepal width, petal length, petal width):
[5.84333333 3.054      3.75866667 1.19866667]


## 6. Comparing NumPy Arrays with Python Lists

The same numbers behave very differently depending on whether they're stored in a list or a
NumPy array.

In [ ]:
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

# Multiplying a list by 2 repeats the whole list
print("List * 2:", python_list * 2)

# Multiplying a NumPy array by 2 multiplies every element
print("Array * 2:", numpy_array * 2)

List * 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array * 2: [ 2  4  6  8 10]


In [ ]:
# Adding two lists together concatenates them, it does not add element-wise
python_list_2 = [10, 20, 30, 40, 50]
print("List + list:", python_list + python_list_2)

# Adding two arrays together adds them element-wise
numpy_array_2 = np.array([10, 20, 30, 40, 50])
print("Array + array:", numpy_array + numpy_array_2)

List + list: [1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
Array + array: [11 22 33 44 55]


## Outcome

This notebook practiced creating one-dimensional and two-dimensional NumPy arrays using real
values from the `Iris_Dataset.csv` file, and explored their `shape`, `ndim`, `size`, and
`dtype` attributes. I performed numerical operations including summary statistics (`mean()`,
`max()`, `min()`, `sum()`, `std()`), element-wise arithmetic, operations between two arrays,
boolean masking to filter values by a condition, and per-column statistics on a 2D array using
`axis=0`. Comparing NumPy arrays directly against plain Python lists showed the key difference
that motivates using NumPy for data science: the same arithmetic operators (`*`, `+`) behave
element-wise on arrays, but repeat or concatenate on lists, which is why NumPy is the
foundation for fast, readable numerical computation on real data.