# Day 14: NumPy Array Reshaping and Stacking

**Dataset:** `Iris_Dataset.csv`

This notebook reshapes arrays into different dimensions and combines multiple arrays using
stacking and concatenation, using real values pulled directly from the Iris dataset.

## 1. Import Libraries and Load the Dataset

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("../datasets/Iris_Dataset.csv")

# Preview the data
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


**Create a 1D array from a real column, and a 2D array from all four numeric feature columns**

In [2]:
petal_length = np.array(df["petal length (cm)"])

feature_columns = ["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]
features = np.array(df[feature_columns])

print("1D array shape:", petal_length.shape)
print("2D array shape:", features.shape)

1D array shape: (150,)
2D array shape: (150, 4)


## 2. Reshaping Arrays

`reshape()` changes an array's dimensions **without changing its data or total number of
elements**. Note that the new shape must have the same total element count as the original.

**Reshape a 1D array into a 2D array**

In [3]:
# petal_length has 150 values. Reshape it into 150 rows, 1 column.
petal_length_2d = petal_length.reshape(150, 1)

print("Original shape:", petal_length.shape)
print("Reshaped shape:", petal_length_2d.shape)
print(petal_length_2d[:5])

Original shape: (150,)
Reshaped shape: (150, 1)
[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]]


**Using `-1` to let NumPy figure out one dimension automatically**

In [4]:
# -1 tells NumPy "figure out this dimension for me" based on the array's total size
petal_length_auto = petal_length.reshape(-1, 1)
print(petal_length_auto.shape)

# Reshape the same 150 values into 15 rows of 10 columns instead
petal_length_15x10 = petal_length.reshape(15, 10)
print(petal_length_15x10.shape)
print(petal_length_15x10)

(150, 1)
(15, 10)
[[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5]
 [1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4 1.7 1.5]
 [1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6]
 [1.6 1.5 1.5 1.4 1.5 1.2 1.3 1.5 1.3 1.5]
 [1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4]
 [4.7 4.5 4.9 4.  4.6 4.5 4.7 3.3 4.6 3.9]
 [3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9]
 [4.8 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5]
 [3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4. ]
 [4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1]
 [6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1]
 [5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5. ]
 [5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6 5.8]
 [6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4]
 [5.6 5.1 5.1 5.9 5.7 5.2 5.  5.2 5.4 5.1]]


**Reshape a 2D array back into 1D with `flatten()` and `ravel()`**

In [5]:
flattened = petal_length_15x10.flatten()
raveled = petal_length_15x10.ravel()

print("flatten() shape:", flattened.shape)
print("ravel() shape:", raveled.shape)
print("Are the values identical?", np.array_equal(flattened, raveled))
print("Back to the original values?", np.array_equal(flattened, petal_length))

flatten() shape: (150,)
ravel() shape: (150,)
Are the values identical? True
Back to the original values? True


**Reshaping only works if the total number of elements matches**

Trying to reshape 150 values into a shape that doesn't hold exactly 150 elements raises an
error.

In [6]:
try:
    bad_reshape = petal_length.reshape(10, 10)   # 10 x 10 = 100, but petal_length has 150 values
except ValueError as e:
    print("ValueError caught:", e)

ValueError caught: cannot reshape array of size 150 into shape (10,10)


## 3. Combining Arrays: Stacking and Concatenation

**Example 1: `np.vstack()`: stack arrays vertically (adding more rows)**

In [7]:
sepal_length = np.array(df["sepal length (cm)"])
sepal_width = np.array(df["sepal width (cm)"])

# Take just the first 5 values of each, to keep the example readable
stacked_vertically = np.vstack((sepal_length[:5], sepal_width[:5]))
print(stacked_vertically)
print("Shape:", stacked_vertically.shape)   # 2 rows, 5 columns

[[5.1 4.9 4.7 4.6 5. ]
 [3.5 3.  3.2 3.1 3.6]]
Shape: (2, 5)


**Example 2: `np.hstack()`: stack arrays horizontally (adding more columns / more values in a row)**

In [8]:
stacked_horizontally = np.hstack((sepal_length[:5], sepal_width[:5]))
print(stacked_horizontally)
print("Shape:", stacked_horizontally.shape)   # one long 1D array, length 10

[5.1 4.9 4.7 4.6 5.  3.5 3.  3.2 3.1 3.6]
Shape: (10,)


**Example 3: `np.concatenate()`: join arrays along a chosen axis**

In [9]:
# Reshape both columns into (150, 1), then concatenate them side-by-side into a (150, 2) array
sepal_length_col = sepal_length.reshape(-1, 1)
sepal_width_col = sepal_width.reshape(-1, 1)

combined = np.concatenate((sepal_length_col, sepal_width_col), axis=1)
print(combined[:5])
print("Shape:", combined.shape)   # 150 rows, 2 columns

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]]
Shape: (150, 2)


**Example 4: Combining the whole `features` array with a new column using `hstack()`**

In [10]:
# Add a new "sepal_area" column onto the existing 2D features array
sepal_area = (sepal_length * sepal_width).reshape(-1, 1)

features_with_area = np.hstack((features, sepal_area))
print(features_with_area[:5])
print("Original features shape:", features.shape)
print("New shape after adding a column:", features_with_area.shape)

[[ 5.1   3.5   1.4   0.2  17.85]
 [ 4.9   3.    1.4   0.2  14.7 ]
 [ 4.7   3.2   1.3   0.2  15.04]
 [ 4.6   3.1   1.5   0.2  14.26]
 [ 5.    3.6   1.4   0.2  18.  ]]
Original features shape: (150, 4)
New shape after adding a column: (150, 5)


## 4. When Is Reshaping Useful?

- **Preparing data for machine learning models.** Many libraries (like scikit-learn) expect a
  2D array shaped `(number_of_samples, number_of_features)`, even if you're only working with
  a single feature. That's exactly why `petal_length.reshape(-1, 1)` was needed above to turn
  a plain 1D column into the 2D shape models expect.
- **Combining separate columns into one dataset.** Reshaping each 1D column into a `(150, 1)`
  column vector, then using `np.concatenate(axis=1)`, is a common way to build a full 2D
  feature matrix out of individual columns computed separately.
- **Flattening for output or storage.** `flatten()`/`ravel()` are useful when a function
  returns a 2D result but you need a plain 1D list of values. For example, before printing,
  saving to a simple file, or passing values into something that expects a flat sequence.
- **Reorganizing data without copying it manually.** Reshaping a large array into a different
  grid layout (like the 150 → 15×10 example above) is far faster and less error-prone than
  manually rebuilding the array element by element.

## Outcome

This notebook practiced reshaping NumPy arrays with `reshape()` (including using `-1` to let
NumPy infer a dimension automatically), converting a 2D array back to 1D with `flatten()` and
`ravel()`, and confirming that reshaping fails with a `ValueError` when the total element count
doesn't match. I combined arrays using four examples: `np.vstack()` to stack rows, `np.hstack()`
to stack values into one longer row, `np.concatenate()` with `axis=1` to join reshaped column
vectors side-by-side into a feature matrix, and `np.hstack()` again to add a newly computed
column onto the existing `features` array. Working through this made clear where reshaping
actually matters in practice, especially reshaping a single column into `(-1, 1)` before it
can be combined with other columns or fed into a model that expects two-dimensional input.