# Day 10: NumPy Indexing and Slicing

**Dataset:** `Wine_Dataset.csv`

This notebook practices selecting individual elements, rows, columns, and ranges from NumPy
arrays using indexing and slicing, using real values pulled directly from the Wine dataset.

## 1. Import Libraries and Load the Dataset

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("../datasets/Wine_Dataset.csv")

# Preview the data
df.head()

,class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735


In [ ]:
# Basic info about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   class                         178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proline         

**Create a 1D array from a single real column, and a 2D array from several real columns**

In [ ]:
alcohol = np.array(df["Alcohol"])

feature_columns = ["Alcohol", "Malic acid", "Ash", "Magnesium", "Color intensity"]
features = np.array(df[feature_columns])

print("1D array shape:", alcohol.shape)
print("2D array shape:", features.shape)
print(features[:5])

1D array shape: (178,)
2D array shape: (178, 5)
[[ 14.23   1.71   2.43 127.     5.64]
 [ 13.2    1.78   2.14 100.     4.38]
 [ 13.16   2.36   2.67 101.     5.68]
 [ 14.37   1.95   2.5  113.     7.8 ]
 [ 13.24   2.59   2.87 118.     4.32]]


## 2. One-Dimensional Indexing

Python indexing is **zero-based**, where the first element is at position `0`, not `1`.

**Example 1: Access the first element (index 0)**

In [ ]:
print(alcohol[0])

14.23


**Example 2: Access the 5th element (index 4)**

In [ ]:
print(alcohol[4])

13.24


**Example 3: Access the last element using negative indexing**

In [ ]:
print(alcohol[-1])

14.13


**Example 4: Access the second-to-last element using negative indexing**

In [ ]:
print(alcohol[-2])

13.17


## 3. Two-Dimensional Indexing

For a 2D array, use `array[row, column]` to select a specific element.

**Example 1: Access a single element: row 0, column 0 (the first wine's Alcohol value)**

In [ ]:
print(features[0, 0])

14.23


**Example 2: Access a single element: row 2, column 3 (the 3rd wine's Magnesium value)**

In [ ]:
print(features[2, 3])

101.0


**Example 3: Access an entire row (all features for one wine)**

In [ ]:
print(features[0])

[ 14.23   1.71   2.43 127.     5.64]


**Example 4: Access an entire column (all wines' Ash values)**

In [ ]:
ash_values = features[:, 2]
print(ash_values[:10])

[2.43 2.14 2.67 2.5  2.87 2.45 2.45 2.61 2.17 2.27]


**Example 5: Access an element using negative row and column indices**

In [ ]:
print(features[-1, -1])   # last row, last column: the last wine's Color intensity

9.2


## 4. Slicing

Slicing uses `start:stop` (and an optional `:step`) to select a **range** of values, instead
of a single element. The `stop` position is never included.

**Example 1: The first 5 alcohol values**

In [ ]:
print(alcohol[0:5])

[14.23 13.2  13.16 14.37 13.24]


**Example 2: Everything from index 5 onward**

In [ ]:
print(alcohol[5:10])   # showing just a small window (5 to 9) for a readable preview

[14.2  14.39 14.06 14.83 13.86]


**Example 3: Everything up to (but not including) index 5**

In [ ]:
print(alcohol[:5])

[14.23 13.2  13.16 14.37 13.24]


**Example 4: Every 2nd value, using a step**

In [ ]:
print(alcohol[0:10:2])

[14.23 13.16 13.24 14.39 14.83]


**Example 5: The last 5 alcohol values, using negative slicing**

In [ ]:
print(alcohol[-5:])

[13.71 13.4  13.27 13.17 14.13]


**Example 6: Slicing a 2D array: the first 3 rows, all columns**

In [ ]:
print(features[0:3, :])

[[ 14.23   1.71   2.43 127.     5.64]
 [ 13.2    1.78   2.14 100.     4.38]
 [ 13.16   2.36   2.67 101.     5.68]]


**Example 7: Slicing a 2D array: all rows, the first 2 columns**

In [ ]:
print(features[:, 0:2][:5])   # showing the first 5 rows for a readable preview

[[14.23  1.71]
 [13.2   1.78]
 [13.16  2.36]
 [14.37  1.95]
 [13.24  2.59]]


**Example 8: Slicing a 2D array: a sub-block of rows and columns**

In [ ]:
print(features[0:3, 1:3])   # rows 0-2, columns 1-2

[[1.71 2.43]
 [1.78 2.14]
 [2.36 2.67]]


## Outcome

This notebook practiced NumPy indexing and slicing using real values from the
`Wine_Dataset.csv` file. For one-dimensional indexing, I accessed elements using positive
indices (the first and fifth values) and negative indices (the last and second-to-last
values). For two-dimensional indexing, I used `array[row, column]` to select single elements,
an entire row, an entire column, and an element using negative indices on both axes. For
slicing, I practiced basic ranges (`start:stop`), open-ended slices (`:stop` and negative
slices from the end), stepped slices, and 2D slices that select a range of rows, a range of
columns, and a sub-block of both at once. This showed how indexing and slicing let you pull
out exactly the data you need from an array, be it a single value, a full row or column, or any
rectangular sub-section, without writing a loop.